apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18, pipelines.kubeflow.org/pipeline_compilation_time: '2025-05-29T19:31:01.684848',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Un pipeline de test simple.",
      "inputs": [{"default": "Aya", "name": "name", "optional": true, "type": "String"}],
      "name": "Hello World Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.18}
spec:
  entrypoint: hello-world-pipeline
  templates:
  - name: hello-world-pipeline
    inputs:
      parameters:
      - {name: name}
    dag:
      tasks:
      - name: say-hello
        template: say-hello
        arguments:
          parameters:
          - {name: name, value: '{{inputs.parameters.name}}'}
  - name: say-hello
    container:
      args: ['Hello {{inputs.parameters.name}}']
      command: [echo]
      image: alpine
    inputs:
      parameters:
      - {name: name}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.18
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters:
    - {name: name, value: Aya}
  serviceAccountName: pipeline-runner
